server:
  port: 0  # 임시 포트, 이후 Config 서버 설정으로 덮어씌움

spring:
  application:
    name: product-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

# Eureka server 연결 (호스트 이름: localhost, 포트: 19090)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
